### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by KagenoMoheji** [mimo456/HealthCheck#1]
- まず，下記エラーが出た
  ```
  Warning: Cannot modify header information - headers already sent by (output started at /src/index.php:22) in /src/index.php on line 27
  ```
  - https://github.com/mimo456/HealthCheck/blob/eef3be3b74b0d69e0299fca7e8028b5bb2f75caa/index.php#L27
- 解決の提案
  - `branch.php`にリダイレクトするのではなく，PHPのimportである`require()`を使ったほうがいいよ

**Comment by mimo456** [comment]
require()って別のファイルのスクリプトを読み込むものですよね、ページ移動できるんですか？！

**Comment by KagenoMoheji** [comment]
@mimo456 
`branch.php`でリダイレクトのコードがあるので，それが`index.html`に挿入される形で実行されますよ～

**Comment by mimo456** [comment]
ああ！そういうことか！！やってみます！！！

**Comment by KagenoMoheji** [comment]
@mimo456 
解決したらCloseしてね！😎

**Comment by mimo456** [comment]
できました！
＞branch.phpにリダイレクトするのではなく，PHPのimportであるrequire()を使ったほうがいいよ
これは処理速度の関係でこうした方がいいということなのでしょうか！？

**Comment by KagenoMoheji** [comment]
@mimo456 
処理速度というよりはリダイレクトで自分に対して通信を発生させるのが無駄なイメージかな

**Comment by mimo456** [comment]
@mimo456
そういうことでしたか！理解しました、ありがとうございました！！
