### ISSUE TITLE
#1 直したあと，`Warning: Cannot modify header information - headers already sent by`

### ISSUE THREAD

**Issue by KagenoMoheji** [mimo456/HealthCheck#2]
- 下記エラーが出た
  ```
  Warning: Cannot modify header information - headers already sent by (output started at /src/index.php:22) in /src/branch.php on line 11
  ```
  - https://github.com/mimo456/HealthCheck/blob/eef3be3b74b0d69e0299fca7e8028b5bb2f75caa/index.php#L22
- 解決の提案
  - 上記コードのコメントアウト
    - `header()`の前にセッションを呼び出すことでHTTPヘッダを操作するためエラーになります

**Comment by mimo456** [comment]
確認のためのsessionが邪魔をしていたのですね、削除しました！ありがとうございます！

**Comment by mimo456** [comment]
確認のためのvar_dumpが邪魔をしていたのですね、削除しました！ありがとうございます！
